version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: APIKEY=$APIKEY AUTHDOMAIN=$AUTHDOMAIN DATABASEURL=$DATABASEURL PROJECTID=$PROJECTID STORAGEBUCKET=$STORAGEBUCKET MESSAGINGSENDERID=$MESSAGINGSENDERID　yarn test 